spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ^2bQ%9?VEr=ex6QJ
    url: jdbc:postgresql://project3-saleforce-test-3.cchrp7vuxlcj.us-east-2.rds.amazonaws.com:5432/project_3
    username: texas_mule

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
server:
  port: 5000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    

        